dist: trusty

language: go

addons:
  sonarcloud:
    organization: "jgengo"


env:
  - GO111MODULE=on GOFLAGS="-mod=vendor"

os:
  - linux
  - osx

go:
  - 1.13.x
  - 1.14.x

git:
  depth: 1

install:
  - go mod download
  - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"

go_import_path: github.com/jgengo/slack_that

script:
  - ./build/test.sh
  - go build -mod=vendor ./... 
  - sonar-scanner
